export const slopeInfo = [
    {
      title: "Blue Slope",
      imgSrc: require("../assets/images/svg/blue-circle.svg").default,
      cork: 4,
      yield: 1.5,
      afterRoi: 0.35,
      snowBall: 0.05,
      dailyYield: 0.4,
      dailySellLimit: 15,
      amount: "30,000",
    },
    {
      title: "Red Slope",
      imgSrc: require("../assets/images/svg/red-rectanle.svg").default,
      cork: 10,
      yield: 2.0,
      afterRoi: 0.9,
      snowBall: 0.1,
      dailyYield: 1.0,
      dailySellLimit: 10,
      amount: "15,000",
    },
    {
      title: "Black Slope",
      imgSrc: require("../assets/images/svg/dia.svg").default,
      cork: 100,
      yield: 2.2,
      afterRoi: 1.0,
      snowBall: 0.1,
      dailyYield: 1.1,
      dailySellLimit: 15,
      amount: "5,000",
    },
    {
      title: "Double Black Diamond",
      imgSrc: require("../assets/images/svg/double-dia.svg").default,
      cork: 1000,
      yield: 2.2,
      afterRoi: 1.0,
      snowBall: 0.125,
      dailyYield: 1.125,
      dailySellLimit: 15,
      amount: "500",
    },
  ];