export const slopeInfo = [
    {
      title: "Blue Slope",
      imgSrc: require("../assets/images/svg/blue-circle.svg").default,
      cork: 3,
      yield: 1.5,
      afterRoi: 0.35,
      snowBall: 0.05,
      dailySellLimit: 15,
      amount: "30,000",
    },
    {
      title: "Red Slope",
      imgSrc: require("../assets/images/svg/red-rectanle.svg").default,
      cork: 10,
      yield: 1.5,
      afterRoi: 0.35,
      snowBall: 0.05,
      dailySellLimit: 15,
      amount: "15,000",
    },
    {
      title: "Double Black",
      imgSrc: require("../assets/images/svg/dia.svg").default,
      cork: 100,
      yield: 1.5,
      afterRoi: 0.35,
      snowBall: 0.05,
      dailySellLimit: 15,
      amount: "5,000",
    },
    {
      title: "Blue Slope",
      imgSrc: require("../assets/images/svg/double-dia.svg").default,
      cork: 1000,
      yield: 1.5,
      afterRoi: 0.35,
      snowBall: 0.05,
      dailySellLimit: 15,
      amount: "500",
    },
  ];